import { Ubuntu } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { navItems } from "@/lib/config";
import { HeroUIProvider } from "@heroui/react";
import { Providers } from "./providers";
// import FluidCursor from "@/components/FluidCursor";
const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ubuntu.variable} antialiased`}>
        {" "}
        {/* <FluidCursor/> */}
        <HeroUIProvider>
          <Providers>
            <div className="relative  w-full">
              <FloatingNav navItems={navItems} />
            </div>
           
              
                {children}
            
     
          </Providers>
        </HeroUIProvider>
      </body>
    </html>
  );
}
